# Generated by Django 2.1 on 2019-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
            preserve_default=False,
        ),
    ]
