# Generated by Django 2.1 on 2019-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0002_fertilizer_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualpayment',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
